### ISSUE TITLE
Can't work

### ISSUE THREAD

**Issue by Danding1314** [alvin0319/TradeNPC#1]
i add paper  => gold axe when i put the paper up but it's not let me to change:(

This plugin is great

**Comment by alvin0319** [comment]
Can you provide more information for me?

ex) your system information, PocketMine-MP Version, etc...

**Comment by Danding1314** [comment]
SOR xd i use error way

**Comment by alvin0319** [comment]
??

**Comment by alvin0319** [comment]
Close this because of not enough information
