### ISSUE TITLE
Duplicate item

### ISSUE THREAD

**Issue by Adam1609** [alvin0319/TradeNPC#5]
I don't record the video but I can explain it. When for example: the Trading menu has 1 diamond sword trade for 64 rotten flesh. And I only have 1 rotten flesh. By clicking too many time on that category causing item duplicate, which player can easily trade for just 1 rotten flesh.

**Comment by Adam1609** [comment]
@alvin0319 can you confirm this?

**Comment by alvin0319** [comment]
Do you edit my plugin?

**Comment by Adam1609** [comment]
I do, but only adding slot 2 and that's it

**Comment by Adam1609** [comment]
Recorded. Can you look into it?
[video-1583668059.zip](https://github.com/alvin0319/TradeNPC/files/4304652/video-1583668059.zip)

**Comment by Adam1609** [comment]
It happened when pressing the category over and over, cause item duplication

**Comment by Adam1609** [comment]
@alvin0319 can you confirm this?

**Comment by alvin0319** [comment]
V2 trading ui doesn't support on this plugin, if you want to use V2 trading ui, use [organization/TradeAPI](https://github.com/organization/TradeAPI) instead of this.
