### ISSUE TITLE
New version: Clicking on NPC will not be able to open the inventory

### ISSUE THREAD

**Issue by Adam1609** [alvin0319/TradeNPC#7]
I have tested with new pmmp version, when clicking on 1 npc that you create, you cannot click on other npc, nor open the inventory

**Comment by Adam1609** [comment]
Oh forgot to mention, the only way to fix this is open another chest and access inventory as quick as possible.

**Comment by alvin0319** [comment]
In 1.16, Inventory open/close handling has been changed, so I don't know how to solve this.
